package entidades;
// Generated 23-11-2024 12:38:45 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private Long idPelicula;
     private Genero genero;
     private String nombrePelicula;
     private int annoPelicula;
     private Date fechaRegistro;

    public Pelicula() {
    }

	
    public Pelicula(String nombrePelicula, int annoPelicula, Date fechaRegistro) {
        this.nombrePelicula = nombrePelicula;
        this.annoPelicula = annoPelicula;
        this.fechaRegistro = fechaRegistro;
    }
    public Pelicula(Genero genero, String nombrePelicula, int annoPelicula, Date fechaRegistro) {
       this.genero = genero;
       this.nombrePelicula = nombrePelicula;
       this.annoPelicula = annoPelicula;
       this.fechaRegistro = fechaRegistro;
    }
   
    public Long getIdPelicula() {
        return this.idPelicula;
    }
    
    public void setIdPelicula(Long idPelicula) {
        this.idPelicula = idPelicula;
    }
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
    public String getNombrePelicula() {
        return this.nombrePelicula;
    }
    
    public void setNombrePelicula(String nombrePelicula) {
        this.nombrePelicula = nombrePelicula;
    }
    public int getAnnoPelicula() {
        return this.annoPelicula;
    }
    
    public void setAnnoPelicula(int annoPelicula) {
        this.annoPelicula = annoPelicula;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

}


